theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: elodiechardon.fr
  summary:
    position: hero
  search:
    active: false  
  breadcrumb:
    position: none
  logo:
    header: /assets/images/chardon.png
    footer: /assets/images/chardon.png
  image_sizes:
    blocks:
      gallery:
        grid:
          mobile:   400
          tablet:   800
          desktop:  1200